### ISSUE TITLE
completion errors

### ISSUE THREAD

**Issue by nadako** [clemos/haxe-sublime-bundle#225]
I started to get these errors since lately and it's very annoying, because it asks to reload my current file because of that and if I agree, I'm losing my changes...
```
Traceback (most recent call last):
  File "C:\Users\korostelev\sublime\sublime_plugin.py", line 304, in on_activated
    callback.on_activated(v)
  File "C:\Users\korostelev\sublime\Data\Packages\Haxe\HaxeComplete.py", line 530, in on_activated
    return self.on_open_file( view )
  File "C:\Users\korostelev\sublime\Data\Packages\Haxe\HaxeComplete.py", line 550, in on_open_file
    self.highlight_errors( view )
  File "C:\Users\korostelev\sublime\Data\Packages\Haxe\HaxeComplete.py", line 504, in highlight_errors
    right = len(line[:right].decode("utf-8"))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 4: unexpected end of data
```

**Comment by r3a1ay** [comment]
Can't reproduce.
Can you provide some test project?

**Comment by r3a1ay** [comment]
Temporarily wrapped the code that is causing the issue in try block.
