### ISSUE TITLE
PermissionError on start

### ISSUE THREAD

**Issue by anonrab** [clemos/haxe-sublime-bundle#241]
Installed bundle with package manager.
Trying to run autocomplete on sublime mac - got error in console:

```
Starting Haxe server on port 6001
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 304, in on_activated
    callback.on_activated(v)
  File "/Users/kolombet/Library/Application Support/Sublime Text 3/Packages/Haxe/HaxeComplete.py", line 571, in on_activated
    return self.on_open_file( view )
  File "/Users/kolombet/Library/Application Support/Sublime Text 3/Packages/Haxe/HaxeComplete.py", line 591, in on_open_file
    self.extract_build_args( view )
  File "/Users/kolombet/Library/Application Support/Sublime Text 3/Packages/Haxe/HaxeComplete.py", line 1002, in extract_build_args
    self.find_build_file( f )
  File "/Users/kolombet/Library/Application Support/Sublime Text 3/Packages/Haxe/HaxeComplete.py", line 941, in find_build_file
    self.find_nmml(folder)
  File "/Users/kolombet/Library/Application Support/Sublime Text 3/Packages/Haxe/HaxeComplete.py", line 666, in find_nmml
    f = codecs.open( build , "r+", "utf-8" , "ignore" )
  File "./codecs.py", line 885, in open
PermissionError: [Errno 13] Permission denied: '/usr/lib/haxelib/flixel/3,3,8/include.xml'
```

haxe -version
3.2.0

haxelib version
3.2.0-rc.3

sublime -version
Sublime Text Build 3083

OSX
10.10.3

**Comment by r3a1ay** [comment]
Are you trying to run autocomplete in **haxeflixel** source folder?
**flixel** library doesn't contain any build file (project.xml). 
This package could not generate autocomplete list without a build file.

@clemos, maybe we should scan only project.xml files (not all *.xml files)?

**Comment by anonrab** [comment]
I trying to autocomplete in my project folder. I suppose, it were some issue with mac os file permissions. Flixel libraries were created with admin access (i don't know why, maybe because installed them with sudo), and user can not modify them. 

When i reinstalled haxe all problems gone. Thanks anyway.

**Comment by JesseTG** [comment]
I still have this issue, but on Kubuntu 15.10.
