### ISSUE TITLE
Completion popup not showing?

### ISSUE THREAD

**Issue by aaulia** [clemos/haxe-sublime-bundle#245]
This is a bit weird, last I check (using Office laptop and Haxe 3.2) I got popup for function parameters, which is a surprise for me since I never had that with haxe sublime before. But at home using Haxe 3.2 and an updated haxe sublime bundle with Sublime 3083, it's not showing me popup.

I've tried adding "haxe_use_popup" to user settings and syntax settings, it still doesn't show.

**Comment by r3a1ay** [comment]
Do you have any error messages in sublime's console?

Try these syntax settings:
```js
"haxe_auto_complete": true,
"haxe_use_popup": true
```

**Comment by aaulia** [comment]
```
Starting Haxe server on port 6001
Package Control: No updated packages
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "features.haxe_hint in C:\Users\aaulia\AppData\Roaming\Sublime Text 3\Installed Packages\Haxe.sublime-package", line 201, in run
  File "features.haxe_hint in C:\Users\aaulia\AppData\Roaming\Sublime Text 3\Installed Packages\Haxe.sublime-package", line 215, in show_popup
  File "features.haxe_format in C:\Users\aaulia\AppData\Roaming\Sublime Text 3\Installed Packages\Haxe.sublime-package", line 71, in format_statement
TypeError: 'NoneType' object is not subscriptable
```

Hmm I'm not sure if this is really problem in haxe sublime part (my installation probably borked?), on my home linux box (dual boot) it works, on my office windows box it works, but on my home windows box it doesn't work.

**Comment by r3a1ay** [comment]
I hope this will help.

**Comment by aaulia** [comment]
Nice! It works now :)
Thank you.
