### ISSUE TITLE
Openfl Project Fails to Build.

### ISSUE THREAD

**Issue by IkonOne** [clemos/haxe-sublime-bundle#251]
ST version: startup, version: 3083 osx x64 channel: stable
haxe-sublime-bundle version: Current...
Python version: Python 2.7.10

When I try to build I get this error in the console(target doesn't matter):

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "HaxeComplete in /Users/MaskedPixel/Library/Application Support/Sublime Text 3/Installed Packages/Haxe.sublime-package", line 430, in run
  File "HaxeComplete in /Users/MaskedPixel/Library/Application Support/Sublime Text 3/Installed Packages/Haxe.sublime-package", line 1188, in run_build
  File "HaxeComplete in /Users/MaskedPixel/Library/Application Support/Sublime Text 3/Installed Packages/Haxe.sublime-package", line 1651, in run_haxe
  File "HaxeComplete in /Users/MaskedPixel/Library/Application Support/Sublime Text 3/Installed Packages/Haxe.sublime-package", line 1476, in run_nme
AttributeError: 'dict' object has no attribute 'syntax'

**Comment by IkonOne** [comment]
Thank you!
