### ISSUE TITLE
FileNotFoundError: resource "Mariana.sublime-color-scheme" not found

### ISSUE THREAD

**Issue by madneon** [clemos/haxe-sublime-bundle#280]
Fresh Sublime Text 3 (build 4169) with no user config and no other packages:

```
reloading plugin Haxe.HaxeComplete
generating meta info summary
Haxe : Reloading haxe module
Haxe : Reloading haxelib module
HAXE : haxelib list 
HAXE : haxelib install 
HAXE : haxelib search 
HAXE : haxelib upgrade 
generating syntax summary
Traceback (most recent call last):
  File "/home/madneon/.config/sublime-text/Installed Packages/Haxe.sublime-package/features/haxe_hint.py", line 86, in parse_scheme
    b = sublime.load_binary_resource(color_scheme)
  File "/opt/lib/sublime-text-3/Lib/python38/sublime.py", line 1211, in load_binary_resource
    raise FileNotFoundError(f'resource "{name}" not found')
FileNotFoundError: resource "Mariana.sublime-color-scheme" not found
None
generating meta info summary
reloading settings Packages/User/Preferences.sublime-settings
Traceback (most recent call last):
  File "/home/madneon/.config/sublime-text/Installed Packages/Haxe.sublime-package/features/haxe_hint.py", line 86, in parse_scheme
    b = sublime.load_binary_resource(color_scheme)
  File "/opt/lib/sublime-text-3/Lib/python38/sublime.py", line 1211, in load_binary_resource
    raise FileNotFoundError(f'resource "{name}" not found')
FileNotFoundError: resource "Mariana.sublime-color-scheme" not found
None
unloading plugin Haxe.HaxeComplete
reloading settings Packages/Haxe/Support/Haxe.sublime-settings
generating syntax summary
Traceback (most recent call last):
  File "/home/madneon/.config/sublime-text/Installed Packages/Haxe.sublime-package/features/haxe_hint.py", line 86, in parse_scheme
    b = sublime.load_binary_resource(color_scheme)
  File "/opt/lib/sublime-text-3/Lib/python38/sublime.py", line 1211, in load_binary_resource
    raise FileNotFoundError(f'resource "{name}" not found')
FileNotFoundError: resource "Mariana.sublime-color-scheme" not found
None
generating meta info summary
reloading settings Packages/User/Preferences.sublime-settings
Traceback (most recent call last):
  File "/home/madneon/.config/sublime-text/Installed Packages/Haxe.sublime-package/features/haxe_hint.py", line 86, in parse_scheme
    b = sublime.load_binary_resource(color_scheme)
  File "/opt/lib/sublime-text-3/Lib/python38/sublime.py", line 1211, in load_binary_resource
    raise FileNotFoundError(f'resource "{name}" not found')
FileNotFoundError: resource "Mariana.sublime-color-scheme" not found
None
```

**Comment by madneon** [comment]
There is also annoying lag on `haxe_hint` - freezing whole Sublime for ~1s on fresh install , and up to couple of seconds on non-fresh Sublime (with other packages, customized config etc).

This is really annoying, considering the fact, that `haxe_hint` is obnoxiously called on some keystrokes like "," and "(", ignoring setting like `"auto_complete": false`.
